<?php

/*
* CHANGE URL BEFORE NODE PRESAVE
* CT : event & intervenant
*/

function galileo_master_node_presave($node){
    if($node->type == "event"){
        $path = array('source' => "node/$node->nid", 'alias' => "evenement/$node->title");
        path_save($path);
    }
    if($node->type == "intervenant"){
        $path = array('source' => "node/$node->nid", 'alias' => "intervenant/$node->title");
        path_save($path);
    }
}


/**
 * Implements hook_init().
 */
function galileo_master_init() {
  global $theme_key;
  if (strpos($theme_key, 'bootstrap') === FALSE) {
    include_once(drupal_get_path('theme', 'bootstrap') . '/includes/process.inc');
  }
}